### ISSUE TITLE
Docker-compose error

### ISSUE THREAD

**Issue by Nikscorp** [gurland/SIGame_web#31]
I got an error while launching service via `docker-compose up`. Can you please upload pre-built images on dockerhub and provide image link in compose file accordingly.
Or please fix the error, I provide log in attachment.

```bash
$ docker-compose ps
           Name                         Command               State             Ports
-----------------------------------------------------------------------------------------------
sigame_web_api_1             uwsgi --ini uwsgi.ini            Up
sigame_web_celery_worker_1   celery worker -A tasks --l ...   Up
sigame_web_db_1              docker-entrypoint.sh postgres    Up       5432/tcp
sigame_web_frontend_1        npm run build                    Exit 1
sigame_web_mongo_1           docker-entrypoint.sh mongod      Up       0.0.0.0:27017->27017/tcp
sigame_web_nginx_1           nginx -g daemon off;             Exit 1
sigame_web_redis_1           docker-entrypoint.sh redis ...   Up       0.0.0.0:6379->6379/tcp

$ docker logs sigame_web_frontend_1 > frontend_error.log 2>&1
$ docker logs sigame_web_nginx_1  >nginx_error.log 2>&1
```

[frontend_error.log](https://github.com/gurland/SIGame_web/files/4390366/frontend_error.log)
[nginx_error.log](https://github.com/gurland/SIGame_web/files/4390368/nginx_error.log)

**Comment by gurland** [comment]
**Thanks for your report**. Apologies for the delayed response – that's mainly because of the project was closed and inactive. 

I fixed this issue by upgrading node version to 8 in frontend service. It was caused by breaking back-compatability with node v6 in `ccs-loader@3.3.1` version. You can see code that invokes error in [this](https://github.com/webpack-contrib/css-loader/pull/1014/files) commit.
